# Generated by Django 3.2.14 on 2023-04-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AirInfo',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('aqi', models.IntegerField(null=True)),
                ('pm25', models.FloatField(null=True)),
                ('temperature', models.IntegerField(null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
            options={
                'db_table': 'air_info',
            },
        ),
        migrations.AddIndex(
            model_name='airinfo',
            index=models.Index(fields=['lat', 'long'], name='index_lat_long'),
        ),
    ]
