# Generated by Django 3.2.14 on 2023-04-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqi', '0002_auto_20230422_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='airinfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
