# Generated by Django 3.2.14 on 2023-04-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqi', '0003_airinfo_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='airinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
