# Generated by Django 3.2.14 on 2023-04-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqi', '0004_airinfo_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='airinfo',
            index=models.Index(fields=['active'], name='index_active'),
        ),
    ]
