version: "3.6"
services:
  db:
    image: postgres:14-alpine
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/teleget/
    volumes:
      - teleget_db_data:/var/lib/postgresql/data/teleget

  api:
    build: ./services/api
    restart: always
    volumes:
      - ./services/api/:/srv/teleget/
      - ./data/:/srv/teleget/data/
    links:
       - db:db
    depends_on:
      - db

  crawler:
    build: ./services/crawler
    restart: always
    volumes:
      - ./services/crawler/:/srv/crawler/
    depends_on:
      - api

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./services/certbot/www:/var/www/certbot/:ro
      - ./services/certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - api
      - certbot

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./services/certbot/www/:/var/www/certbot/:rw
      - ./services/certbot/conf/:/etc/letsencrypt/:rw

networks:
    teleget:
        driver: bridge
volumes:
  teleget_db_data:
    name: teleget_db_data
