version: "3.6"
services:
  db:
    image: postgres:14-alpine
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - teleget_db_data:/var/lib/postgresql/data/pgdata

    networks:
        - teleget
  api:
    build: ./services/api
    ports:
    - "8000:8000"
    restart: always
    volumes:
      - ./services/api/:/srv/teleget/
      - ./data/:/srv/teleget/data/
    links:
       - db:db
    networks:
        - teleget
    depends_on:
      - db
  scraper:
    build: ./services/scraper
    restart: always
    volumes:
      - ./services/scraper/:/srv/scraper/
    networks:
        - teleget

networks:
    teleget:
        driver: bridge
volumes:
  teleget_db_data:
    name: teleget_db_data
